### ISSUE TITLE
%{ubuntu} is malformed and does not work

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild-0.11.3#2]
I was trying to use the `%{ubuntu}` variable to check for the release and install the appropriate service configuration files, but I ran into a couple of problems.

First, `%{ubuntu}` is defined as "XX.YY", which is invalid in `rpmbuild`. 

It throws an error like this: `error: cbs.spec:59: bad %if condition`. 

It must be an integer. This explains why SUSE's `%{suse_version}` is something like `1320` for openSUSE 13.2.

Secondly, even if I ignore that issue and try to use it, it doesn't work. Here's a sample from my spec:

```
%if 0%{?ubuntu} > 0 && 0%{?ubuntu} < 15.04 
mkdir %{buildroot}%{_upstart_jobsdir} 
mv ubuntu/*.upstart %{buildroot}%{_upstart_jobsdir} 
mv %{buildroot}%{_upstart_jobsdir}/%{name}-client.upstart %{buildroot}%{_upstart_jobsdir}/%{name}-client.conf 
mv %{buildroot}%{_upstart_jobsdir}/%{name}-server.upstart %{buildroot}%{_upstart_jobsdir}/%{name}-server.conf 
%else 
mkdir -p %{buildroot}%{_unitdir} 
cp %{SOURCE1} %{buildroot}%{_unitdir} 
cp %{SOURCE2} %{buildroot}%{_unitdir} 
%endif
```
The resultant package on *all* versions of Ubuntu includes only the upstart job files, even though it should clearly use the systemd service files. I'm not sure if the same issue would come up with conditional logic for using different behavior for different Debian versions through `%{debian}`, too...

**Comment by ascherer** [comment]
The whole hodge-podge of debbuild's "system detection" is alien to me. I will forward this to the original author to fix.

**Comment by ascherer** [comment]
The `%if...%else...%endif` construct didn't work properly; the `%else` part was _always_ skipped. Please try the most recent version of debbuild – it _does_ write extra diagnostics at this time.

**Comment by Conan-Kudo** [comment]
I tried to test using [a spec for GNU Hello on Open Build Service](https://build.opensuse.org/package/view_file/home:Pharaoh_Atem/hello/hello.spec?expand=1), but it broke on `make install`, as you can see from [this log](https://build.opensuse.org/build/home:Pharaoh_Atem/Debian_7.0/x86_64/hello/_log).

**Comment by Conan-Kudo** [comment]
The latest code from git seems to still not work, as you can see from [this log](https://build.opensuse.org/build/home:Pharaoh_Atem/xUbuntu_15.04/x86_64/hello/_log).

The relevant snippet from the log below:
```
[  249s] -----------------------------------------------------------------
[  249s] I have the following modifications for hello.spec:
[  249s] 3c3
[  249s] < Release:         4%{?dist}
[  249s] ---
[  249s] > Release:         32.1%{?dist}
[  249s] Running build time source services...
[  249s] -----------------------------------------------------------------
[  249s] ----- building hello.spec (user abuild)
[  249s] -----------------------------------------------------------------
[  249s] -----------------------------------------------------------------
[  249s] + exec debbuild -ba --define _srcdefattr (-,root,root) --define disturl obs://build.opensuse.org/home:Pharaoh_Atem/xUbuntu_15.04/1012d4fb45eaf7a8dc3abf003764f551-hello /usr/src/debian/SOURCES/hello.spec
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1900.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1909.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1913.
[  250s] Use of uninitialized value $macrostring in pattern match (m//) at /usr/bin/debbuild line 1916.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1924.
[  250s] Use of uninitialized value $macrostring in pattern match (m//) at /usr/bin/debbuild line 1930.
[  250s] Use of uninitialized value $macrostring in pattern match (m//) at /usr/bin/debbuild line 1957.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1966.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1967.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1968.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1969.
[  250s] Use of uninitialized value $macrostring in substitution (s///) at /usr/bin/debbuild line 1970.
[  250s] Deep recursion on subroutine "main::expandmacros" at /usr/bin/debbuild line 1961, <SPECFILE> line 10.
[  292s] [  263.310462] Out of memory: Kill process 17472 (debbuild) score 952 or sacrifice child
[  292s] [  263.311399] Killed process 17472 (debbuild) total-vm:2957584kB, anon-rss:850036kB, file-rss:1012kB
[  293s] ### WATCHDOG MARKER START ###
[  298s] [  269.794249] SysRq : Power Off
[  298s] [  269.812858] reboot: Power down
[  300s] ### WATCHDOG MARKER END ###
```

**Comment by ascherer** [comment]
I have a version of debbuild that produces a clean build already! However, there are at least half a dozen buglets yet to fix tightly. Please wait for the next bunch of commits.

**Comment by Conan-Kudo** [comment]
@ascherer Okay.

**Comment by ascherer** [comment]
[Success!](https://github.com/ascherer/debbuild-0.11.3/blob/master/hello.log)

**Comment by ascherer** [comment]
[Success!](https://github.com/ascherer/debbuild-0.11.3/blob/master/hello.log)
