### ISSUE TITLE
[RFE] Implement macro parser and add debbuild specific macro search paths

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild-0.11.3#5]
Currently, `debbuild` maintains macros within itself, meaning that the addition of macros must be added to the script in order to have them globally available.

It would make sense implement a macro parser like `rpmbuild` has, and split the macros out into something like `/usr/lib/debbuild/macros`, and extra macros could be defined in `/usr/lib/debbuild/macros.d/macros.*` and `/etc/debbuild/macros` and `/etc/debbuild/macros.*`, like how rpmbuild does.

This would allow for debbuild-specific macros (that could potentially be set up to clobber the ones it pulls in from rpm's macro locations, if those were supported too) to be stored in a unique place that is uniquely owned by debbuild.

More importantly, it makes it easier to take macros used in RPM based distributions like Fedora, SUSE, Mageia, etc. and "Debian-ize" them to make more useful Debian packages without having to modify `debbuild` all the time. For example, it would make using the `macros.systemd`, `macros.cmake`, and other macros files shipped by upstream projects or distributions directly useful with `debbuild`.

**Comment by ascherer** [comment]
The current form of debbuild's macro processing can at best be called rudimentary. Only quite recently, it acquired a few more useful features like macro expansion for external programmes (from /usr/lib/rpm/macros), `$(echo $HOME)`, and `${getenv:HOME}`. Unfortunately, the implementation seems to have grown over a decade and in its current form probably is not suitable for extension.

**Comment by ascherer** [comment]
Mental note: create debbuild's own "macros" file, sufficient to run `debbuild` in its current form. Reference it in `debbuild.spec` and install it as `/usr/lib/debbuild/macros`.

**Comment by ascherer** [comment]
After a long day of hacking, debbuild has learned a few new and improved things, and has lost some fat along the way. Macro processing not yet complete, but on good course.

**Comment by ascherer** [comment]
Idea re macro processor: use external library with full-blown rpm version.

**Comment by Conan-Kudo** [comment]
@ascherer Is that possible? That'd be pretty neat if it could do that, though I suppose that would force a dependency on RPM for debbuild to work (not really the end of the world when being used in build systems, I imagine).

Does librpm/librpmbuild even have Perl bindings that you can use? I only know of the RPM Python bindings, not any Perl ones...

**Comment by ascherer** [comment]
Is there such a thing as librpm(build) already?

**Comment by ascherer** [comment]
[Indeed there is!](http://rpm.org/api/4.8.0/group__rpmmacro.html)

**Comment by Conan-Kudo** [comment]
@ascherer Yeah, librpmbuild has been around for quite a while, so you could use it. But as far as I'm aware, there are no Perl bindings for it.

**Comment by ascherer** [comment]
Re rewrite in [your favorite language]: debbuild does what I require (since about 2008). Most of its inner workings are completely uncharted territory for me. The recent frenzy of Perlish hackery certainly improved on the "user interface" (cli and spec), but I really don't fancy digging much deeper. (It seems I already have flooded KD even with my initial submissions up to SVN@210.)
